services:
  ollama:
    image: dustynv/ollama:r36.4.0
    container_name: ollama
    restart: unless-stopped

    ports:
      - "11434:11434"

    environment:
      OLLAMA_MODELS: /models
      OLLAMA_HOST: 0.0.0.0:11434
      OLLAMA_LOGS: /data/logs/ollama.log

    volumes:
      - /ssd/ollama/models:/models
      - /ssd/ollama/data:/root/.ollama
      - /ssd/ollama/logs:/data/logs

    entrypoint: ["/bin/bash","-lc","exec ollama serve"]

    runtime: nvidia

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped

    ports:
      - "3000:8080"

    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_URL=http://localhost:3000
      - ENABLE_WEB_SEARCH=true
      - WEB_SEARCH_ENGINE=duckduckgo
      - ENABLE_PERSISTENT_CONFIG=true
      - HF_HUB_DISABLE_HF_TRANSFER=1
      - HF_HOME=/app/backend/data/hf-home
      - TRANSFORMERS_CACHE=/app/backend/data/hf-cache
      - USER_AGENT=OpenWebUI-on-Jetson

    volumes:
      - /ssd/openwebui/data:/app/backend/data
      - /ssd/openwebui/library:/library:ro
    depends_on:
      - ollama
    dns:
      - 1.1.1.1
      - 8.8.8.8
    runtime: nvidia
